### ISSUE TITLE
Hide duplicate correlations

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#11]
<img width="387" alt="Screen Shot 2022-01-06 at 12 55 45" src="https://user-images.githubusercontent.com/7927356/148428361-9f977698-b5c2-4fe8-b0b7-32ead2cea1ba.png">

**Comment by SkepticMystic** [comment]
Added a check to avoid duplicate correlations when both fields are numeric. But other pairs of types may still show doubles
