### ISSUE TITLE
Blank Correlation View

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#14]
<img width="435" alt="Screen Shot 2022-01-06 at 14 17 09" src="https://user-images.githubusercontent.com/7927356/148438624-1a37ed93-6e40-4076-bd9b-a7990afed994.png">

Reloaded my vault. Loaded up the view. Tried refreshing. Tried closing and loading the view again.

**Comment by arminta7** [comment]
<img width="443" alt="Screen Shot 2022-01-06 at 14 18 43" src="https://user-images.githubusercontent.com/7927356/148438794-c07f155e-7756-47f1-8a9b-27ed981055fb.png">
 
Just refreshed again and now it looks like this.

**Comment by SkepticMystic** [comment]
Yes, so I'm not sure why it doesn't load the first time sometimes, but in the latest version pressing Refresh should fix it. I'll try find the underlying issue though

**Comment by arminta7** [comment]
Seems fixed
