### ISSUE TITLE
[FR]: Click correlation pair in sidebar to show chart modal

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#16]
I keep finding myself wanting to select the various pairs in the sidebar correlation view to bring up more details, like the chart modal. This would be a great feature/shortcut. I'm sure a similar thing in the upcoming overview/summary view would be nice too!

**Comment by SkepticMystic** [comment]
Ahh good idea!
I can make it so when you right click a row in the table, you have the option to open up the Chart or Stats modal on that field
