### ISSUE TITLE
[FR] Display number of data points

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#18]
I'd love to be able to see at a glance how many data points there are to see how meaningful the stats are. Maybe when hovering over in the correlations view, and displayed in the stats and charts modals? Open to ideas.

**Comment by SkepticMystic** [comment]
I can totally do this. 
- For Correlation View, I'll make it so that hovering over that row of the table shows a tooltip with the number of data points
- For Stats View, I'll add a row to the table
- For Chart View, I'll add it next to the correlation value
