### ISSUE TITLE
[FR]: option to permanently hide specific correlation pairs

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#25]
Some fields are obviously always going to be related or are just pairs I don't care about. Would be nice to be able to hide them from the correlation view so they don't show up again. Maybe maintain a list to see what's been hidden if I want to add any back.

**Comment by person-al** [comment]
@SkepticMystic I'll take care of this after the correlation refactor. It'll be super easy to do once I've changed how we run the correlations.
