### ISSUE TITLE
Correlation Summary doesn't seem to work for binary/link type fields. 

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#37]
<img width="405" alt="Screen Shot 2022-01-11 at 13 05 43" src="https://user-images.githubusercontent.com/7927356/148997387-20638201-d835-4853-be17-990ad3835708.png">

<img width="395" alt="Screen Shot 2022-01-11 at 13 06 49" src="https://user-images.githubusercontent.com/7927356/148997529-3a8d86e4-aaab-45a4-a290-3f828cda3fc6.png">

**Comment by person-al** [comment]
@arminta7 A couple changes in an upcoming fix for this:
1. All the fields in the report dropdown will be in alphabetical order now
2. All list field types will be in the dropdown in a specific format: `field.listValue`. For example, `Bacon` will appear as `foods.Bacon`.

Let me know your thoughts.
