### ISSUE TITLE
Chart view not taking into account 0 values

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#4]
For fields like Stress:: I put a 1 or a 0. When I pull up the chart view and compare Stress and Hydrocortisone I'm not seeing all of my data points. 
<img width="694" alt="Screen Shot 2022-01-06 at 11 55 21" src="https://user-images.githubusercontent.com/7927356/148420070-128614e5-549e-4698-b551-374f67a6f49f.png">
<img width="1486" alt="Screen Shot 2022-01-06 at 11 55 49" src="https://user-images.githubusercontent.com/7927356/148420142-dfa44add-a082-428a-8649-0b3410986059.png">

**Comment by SkepticMystic** [comment]
Fixed in next release :)
