### ISSUE TITLE
[FR]: Overall summary report

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#6]
As discussed. 

Most positively and negatively correlated fields in the entire vault. most unrelated in the entire vault. Ability to choose one field and see the same for that one specifically.

**Comment by person-al** [comment]
@arminta7 do you have a preference between seeing the summary report in Obsidian via exporting the data? I assume the current data export feature does most of the exporting that you need and the summary report would be best inside of Obsidian? But just want to be sure.

**Comment by person-al** [comment]
There's a PR out to introduce the baseline Correlation Summary Report. I'm going to make a new issue to track the "show me everything related to a specific field" request in this issue. Will link in this thread when I do that.

**Comment by arminta7** [comment]
> @arminta7 do you have a preference between seeing the summary report in Obsidian via exporting the data? I assume the current data export feature does most of the exporting that you need and the summary report would be best inside of Obsidian? But just want to be sure.

Sorry I didn't see this. Inside of Obsidian is perfect
