### ISSUE TITLE
Only show applicable fields in stats modal. 

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#9]
It's probably not useful to show the binary fields in the stats modal dropdown. Plus they don't work. Maybe some other stats can be shown that would be applicable to those?

Also, starting the dropdown as blank instead of prepopulated with the first field might be best. I keep finding myself needing to delete and type something else.

**Comment by SkepticMystic** [comment]
In a new release, I've fixed a bug. So the binary fields should work now.
The mean shows the proportion of that field
![image](https://user-images.githubusercontent.com/70717676/149272919-4b602c5e-0866-4601-8097-2f6a434bb88d.png)
